site_name: Getting Started with MapServer
site_description: "MapServer is an Open Source platform for publishing spatial data and interactive mapping applications to the web. This workshop will cover publishing geospatial data to the Web using MapServer in support of the suite of OGC API standards."
site_author: The MapServer community
copyright: "&copy; 2024 Seth Girvin and the MapServer community"
site_url: https://geographika.github.io/getting-started-with-mapserver
repo_url: https://github.com/geographika/getting-started-with-mapserver
nav:
    - Home: index.md
    - Workshop Environment Setup: setup.md
    - Introduction:
        - Introduction: introduction/introduction.md
        - Docker: introduction/docker.md        
        - MapServer: introduction/mapserver.md
        - Command Line: introduction/commandline.md
        - OpenLayers: introduction/openlayers.md
    - Mapfile:
        - Lines: mapfile/lines.md    
        - Points: mapfile/points.md
        - Labels: mapfile/labels.md
        - Polygons: mapfile/polygons.md
    - Inputs:
        - Raster Data: inputs/raster.md
        - Vector Data: inputs/vector.md
        - Databases: inputs/databases.md
    - Outputs:
        - WMS: outputs/wms.md
        - WFS: outputs/wfs.md
        - Tiles: outputs/tiles.md
        - Vector Tiles: outputs/vector-tiles.md
        - OGC Features API: outputs/ogcfeatures.md
    - Advanced:
        - SLD: advanced/sld.md
        - Vector Symbols: advanced/symbols.md        
        - Clusters: advanced/clusters.md
        - MapScript: advanced/mapscript.md
    - Summary: summary.md
    - Credits and Thanks: credits.md

use_directory_urls: true

theme:
    name: material
    palette:
        # See https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#color-scheme
        # Default is indigo (blue)
        scheme: mapserver
    features:
        - navigation.indexes
        - content.code.copy
        - content.code.select
    favicon: assets/favicon.ico
    logo: assets/images/mapserver-logo.png

plugins:
    - search

markdown_extensions:
    - meta # option to add some meta tags on top, title, author, date, etc
    - admonition # adds the note, question, tip boxes, eg: !!! tip "my tip"
    - pymdownx.details # advanced collapsible panels
    - pymdownx.superfences # advanced features; such as line number, flow chart, python shell
    - pymdownx.tabbed:
          alternate_style: true
    - pymdownx.highlight:
          anchor_linenums: true
          line_spans: __span
          pygments_lang_class: true
    - pymdownx.inlinehilite
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#embedding-external-files
    - pymdownx.snippets:
          check_paths: true
          base_path: ["../../workshop/exercises/mapfiles", "../../workshop/exercises/app/js", "../../workshop/exercises/app/data", "./docs"]
    - footnotes # notes bottom of page
    - attr_list # used to size images
    - md_in_html # used to size images

extra_css:
    # mapserver primary color with light and dark variations from material.io
    # https://material.io/resources/color/#!/?view.left=0&view.right=1
    - assets/stylesheets/mapserver.css
    - assets/stylesheets/termynal.css
    - assets/stylesheets/custom.css

extra_javascript:
    - assets/javascripts/termynal.js
    - assets/javascripts/custom.js
