name: Deploy application ⚙️

on:
  push:
    branches:
      - main
    paths:
      - 'workshop/exercises/app/**'
      - '.github/workflows/deploy.app.yml'

defaults:
  run:
    working-directory: workshop/exercises/app

jobs:
  build:
    name: Build and Deploy JavaScript application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build website
        run: |
          npm install
          npm run build
      - name: Deploy 📦
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          publish_repo: geographika/getting-started-with-mapserver-demo
